project_name: firehose-ethereum

release:
  draft: true
  github:
    owner: streamingfast
    name: firehose-ethereum
  name_template: '{{.Tag}}'

builds:
  - id: darwin-amd64
    main: ./cmd/fireeth
    binary: fireeth
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: darwin-arm64
    main: ./cmd/fireeth
    binary: fireeth
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: linux-amd64
    main: ./cmd/fireeth
    binary: fireeth
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: firehose-ethereum
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
    name_template: >-
      fireeth_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ tolower .Arch }}{{ end }}
    format: tar.gz
    files:
    - LICENSE
    - README.md

snapshot:
  name_template: '{{ .Tag }}-next'

checksum:
  name_template: checksums.txt

changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc

dist: dist

brews:
  - name: firehose-ethereum
    ids:
    - firehose-ethereum
    tap:
      owner: streamingfast
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@streamingfast.io
    homepage: "https://github.com/streamingfast/firehose-ethereum"
    description: "Firehose on Ethereum stack"
    license: "Apache-2.0"
