env_files:
  github_token: ~/.config/goreleaser/github_token

builds:
  - id: darwin-amd64
    main: ./cmd/fireeth
    binary: fireeth
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
      - C_INCLUDE_PATH=/usr/local/osxcross/include/amd64
      - LIBRARY_PATH=/usr/local/osxcross/lib/amd64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: darwin-arm64
    main: ./cmd/fireeth
    binary: fireeth
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=oa64-clang
      - CXX=oa64-clang++
      - C_INCLUDE_PATH=/usr/local/osxcross/include/arm64
      - LIBRARY_PATH=/usr/local/osxcross/lib/arm64
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: linux-amd64
    main: ./cmd/fireeth
    binary: fireeth
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - C_INCLUDE_PATH=/usr/x86_64-linux-gnu/include
      - LIBRARY_PATH=/usr/x86_64-linux-gnu/lib
    flags:
      - -trimpath
      - -mod=readonly
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: firehose-ethereum
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
    name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ tolower .Arch }}{{ end }}
    format: tar.gz
    files:
    - LICENSE
    - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^GitBook:'

release:
  draft: true
  name_template: '{{ .Tag }}'
  target_commitish: '{{ .Commit }}'

brews:
  - name: firehose-ethereum
    ids:
    - firehose-ethereum
    tap:
      owner: streamingfast
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@streamingfast.io
    homepage: "https://github.com/streamingfast/firehose-ethereum"
    description: "StreamingFast CLI for 'firehose-ethereum'"
    license: "Apache-2.0"