ARG CHAIN_VERSION=geth-latest
ARG SF_VERSION=latest

FROM ghcr.io/streamingfast/go-ethereum:$CHAIN_VERSION as chain
FROM ghcr.io/streamingfast/sf-ethereum:$SF_VERSION

COPY --from=chain /app/geth /app/geth

COPY tools/sfeth/motd_node_manager /etc/
COPY tools/sfeth/99-sfeth-node-manager.sh /etc/profile.d/
COPY tools/sfeth/scripts/. /usr/local/bin/
