ARG CHAIN_VERSION=geth-latest
ARG SF_VERSION=latest
FROM ghcr.io/streamingfast/go-ethereum:$CHAIN_VERSION as chain
FROM ghcr.io/streamingfast/sf-ethereum:$SF_VERSION
COPY --from=chain /app/geth /app/geth
