ARG CORE_VERSION=b2cf970

FROM golang:1.22-alpine as build
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . ./

RUN  go build  ./cmd/fireeth

#######

FROM ghcr.io/streamingfast/firehose-core:$CORE_VERSION as core

COPY --from=build /app/fireeth /app/fireeth