// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.7.1
// source: dfuse/ethereum/trxstream/v1/trxstream.proto

package pbtrxstream

import (
	reflect "reflect"
	sync "sync"

	proto "github.com/golang/protobuf/proto"
	v1 "github.com/streamingfast/sf-ethereum/pb/dfuse/ethereum/codec/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TransactionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dfuse_ethereum_trxstream_v1_trxstream_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dfuse_ethereum_trxstream_v1_trxstream_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescGZIP(), []int{0}
}

var File_dfuse_ethereum_trxstream_v1_trxstream_proto protoreflect.FileDescriptor

var file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDesc = []byte{
	0x0a, 0x2b, 0x64, 0x66, 0x75, 0x73, 0x65, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d,
	0x2f, 0x74, 0x72, 0x78, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x72,
	0x78, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x64,
	0x66, 0x75, 0x73, 0x65, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2e, 0x74, 0x72,
	0x78, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x1a, 0x23, 0x64, 0x66, 0x75, 0x73,
	0x65, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x63,
	0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x14, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x32, 0x7c, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x67, 0x0a, 0x0c, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2f, 0x2e, 0x64, 0x66, 0x75,
	0x73, 0x65, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2e, 0x74, 0x72, 0x78, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x64, 0x66,
	0x75, 0x73, 0x65, 0x2e, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2e, 0x63, 0x6f, 0x64,
	0x65, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x30, 0x01, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x64, 0x66, 0x75, 0x73, 0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x64, 0x66, 0x75, 0x73, 0x65,
	0x2d, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x70, 0x62, 0x2f, 0x64, 0x66, 0x75,
	0x73, 0x65, 0x2f, 0x65, 0x74, 0x68, 0x65, 0x72, 0x65, 0x75, 0x6d, 0x2f, 0x74, 0x72, 0x78, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x62, 0x74, 0x72, 0x78, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescOnce sync.Once
	file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescData = file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDesc
)

func file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescGZIP() []byte {
	file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescOnce.Do(func() {
		file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescData = protoimpl.X.CompressGZIP(file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescData)
	})
	return file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDescData
}

var file_dfuse_ethereum_trxstream_v1_trxstream_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dfuse_ethereum_trxstream_v1_trxstream_proto_goTypes = []interface{}{
	(*TransactionRequest)(nil), // 0: dfuse.ethereum.trxstream.v1.TransactionRequest
	(*v1.Transaction)(nil),     // 1: dfuse.ethereum.codec.v1.Transaction
}
var file_dfuse_ethereum_trxstream_v1_trxstream_proto_depIdxs = []int32{
	0, // 0: dfuse.ethereum.trxstream.v1.TransactionStream.Transactions:input_type -> dfuse.ethereum.trxstream.v1.TransactionRequest
	1, // 1: dfuse.ethereum.trxstream.v1.TransactionStream.Transactions:output_type -> dfuse.ethereum.codec.v1.Transaction
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dfuse_ethereum_trxstream_v1_trxstream_proto_init() }
func file_dfuse_ethereum_trxstream_v1_trxstream_proto_init() {
	if File_dfuse_ethereum_trxstream_v1_trxstream_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dfuse_ethereum_trxstream_v1_trxstream_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dfuse_ethereum_trxstream_v1_trxstream_proto_goTypes,
		DependencyIndexes: file_dfuse_ethereum_trxstream_v1_trxstream_proto_depIdxs,
		MessageInfos:      file_dfuse_ethereum_trxstream_v1_trxstream_proto_msgTypes,
	}.Build()
	File_dfuse_ethereum_trxstream_v1_trxstream_proto = out.File
	file_dfuse_ethereum_trxstream_v1_trxstream_proto_rawDesc = nil
	file_dfuse_ethereum_trxstream_v1_trxstream_proto_goTypes = nil
	file_dfuse_ethereum_trxstream_v1_trxstream_proto_depIdxs = nil
}
