// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: sf/ethereum/substreams/v1/rpc.proto

package pbethss

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcCalls struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Calls         []*RpcCall             `protobuf:"bytes,1,rep,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcCalls) Reset() {
	*x = RpcCalls{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcCalls) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCalls) ProtoMessage() {}

func (x *RpcCalls) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCalls.ProtoReflect.Descriptor instead.
func (*RpcCalls) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *RpcCalls) GetCalls() []*RpcCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

type RpcCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToAddr        []byte                 `protobuf:"bytes,1,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcCall) Reset() {
	*x = RpcCall{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcCall) ProtoMessage() {}

func (x *RpcCall) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcCall.ProtoReflect.Descriptor instead.
func (*RpcCall) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *RpcCall) GetToAddr() []byte {
	if x != nil {
		return x.ToAddr
	}
	return nil
}

func (x *RpcCall) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RpcResponses struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Responses     []*RpcResponse         `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponses) Reset() {
	*x = RpcResponses{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponses) ProtoMessage() {}

func (x *RpcResponses) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponses.ProtoReflect.Descriptor instead.
func (*RpcResponses) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *RpcResponses) GetResponses() []*RpcResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type RpcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Raw           []byte                 `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
	Failed        bool                   `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcResponse) Reset() {
	*x = RpcResponse{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcResponse) ProtoMessage() {}

func (x *RpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcResponse.ProtoReflect.Descriptor instead.
func (*RpcResponse) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *RpcResponse) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *RpcResponse) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type RpcGetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Block         string                 `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcGetBalanceRequest) Reset() {
	*x = RpcGetBalanceRequest{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcGetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGetBalanceRequest) ProtoMessage() {}

func (x *RpcGetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGetBalanceRequest.ProtoReflect.Descriptor instead.
func (*RpcGetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{4}
}

func (x *RpcGetBalanceRequest) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *RpcGetBalanceRequest) GetBlock() string {
	if x != nil {
		return x.Block
	}
	return ""
}

type RpcGetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       []byte                 `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Failed        bool                   `protobuf:"varint,2,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcGetBalanceResponse) Reset() {
	*x = RpcGetBalanceResponse{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcGetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGetBalanceResponse) ProtoMessage() {}

func (x *RpcGetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGetBalanceResponse.ProtoReflect.Descriptor instead.
func (*RpcGetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{5}
}

func (x *RpcGetBalanceResponse) GetBalance() []byte {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *RpcGetBalanceResponse) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

type RpcGetBalanceRequests struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Requests      []*RpcGetBalanceRequest `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcGetBalanceRequests) Reset() {
	*x = RpcGetBalanceRequests{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcGetBalanceRequests) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGetBalanceRequests) ProtoMessage() {}

func (x *RpcGetBalanceRequests) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGetBalanceRequests.ProtoReflect.Descriptor instead.
func (*RpcGetBalanceRequests) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{6}
}

func (x *RpcGetBalanceRequests) GetRequests() []*RpcGetBalanceRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type RpcGetBalanceResponses struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Responses     []*RpcGetBalanceResponse `protobuf:"bytes,1,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcGetBalanceResponses) Reset() {
	*x = RpcGetBalanceResponses{}
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcGetBalanceResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGetBalanceResponses) ProtoMessage() {}

func (x *RpcGetBalanceResponses) ProtoReflect() protoreflect.Message {
	mi := &file_sf_ethereum_substreams_v1_rpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGetBalanceResponses.ProtoReflect.Descriptor instead.
func (*RpcGetBalanceResponses) Descriptor() ([]byte, []int) {
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP(), []int{7}
}

func (x *RpcGetBalanceResponses) GetResponses() []*RpcGetBalanceResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

var File_sf_ethereum_substreams_v1_rpc_proto protoreflect.FileDescriptor

const file_sf_ethereum_substreams_v1_rpc_proto_rawDesc = "" +
	"\n" +
	"#sf/ethereum/substreams/v1/rpc.proto\x12\x19sf.ethereum.substreams.v1\"D\n" +
	"\bRpcCalls\x128\n" +
	"\x05calls\x18\x01 \x03(\v2\".sf.ethereum.substreams.v1.RpcCallR\x05calls\"6\n" +
	"\aRpcCall\x12\x17\n" +
	"\ato_addr\x18\x01 \x01(\fR\x06toAddr\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"T\n" +
	"\fRpcResponses\x12D\n" +
	"\tresponses\x18\x01 \x03(\v2&.sf.ethereum.substreams.v1.RpcResponseR\tresponses\"7\n" +
	"\vRpcResponse\x12\x10\n" +
	"\x03raw\x18\x01 \x01(\fR\x03raw\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\bR\x06failed\"F\n" +
	"\x14RpcGetBalanceRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x14\n" +
	"\x05block\x18\x02 \x01(\tR\x05block\"I\n" +
	"\x15RpcGetBalanceResponse\x12\x18\n" +
	"\abalance\x18\x01 \x01(\fR\abalance\x12\x16\n" +
	"\x06failed\x18\x02 \x01(\bR\x06failed\"d\n" +
	"\x15RpcGetBalanceRequests\x12K\n" +
	"\brequests\x18\x01 \x03(\v2/.sf.ethereum.substreams.v1.RpcGetBalanceRequestR\brequests\"h\n" +
	"\x16RpcGetBalanceResponses\x12N\n" +
	"\tresponses\x18\x01 \x03(\v20.sf.ethereum.substreams.v1.RpcGetBalanceResponseR\tresponsesBWZUgithub.com/streamingfast/firehose-ethereum/types/pb/sf/ethereum/substreams/v1;pbethssb\x06proto3"

var (
	file_sf_ethereum_substreams_v1_rpc_proto_rawDescOnce sync.Once
	file_sf_ethereum_substreams_v1_rpc_proto_rawDescData []byte
)

func file_sf_ethereum_substreams_v1_rpc_proto_rawDescGZIP() []byte {
	file_sf_ethereum_substreams_v1_rpc_proto_rawDescOnce.Do(func() {
		file_sf_ethereum_substreams_v1_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sf_ethereum_substreams_v1_rpc_proto_rawDesc), len(file_sf_ethereum_substreams_v1_rpc_proto_rawDesc)))
	})
	return file_sf_ethereum_substreams_v1_rpc_proto_rawDescData
}

var file_sf_ethereum_substreams_v1_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_sf_ethereum_substreams_v1_rpc_proto_goTypes = []any{
	(*RpcCalls)(nil),               // 0: sf.ethereum.substreams.v1.RpcCalls
	(*RpcCall)(nil),                // 1: sf.ethereum.substreams.v1.RpcCall
	(*RpcResponses)(nil),           // 2: sf.ethereum.substreams.v1.RpcResponses
	(*RpcResponse)(nil),            // 3: sf.ethereum.substreams.v1.RpcResponse
	(*RpcGetBalanceRequest)(nil),   // 4: sf.ethereum.substreams.v1.RpcGetBalanceRequest
	(*RpcGetBalanceResponse)(nil),  // 5: sf.ethereum.substreams.v1.RpcGetBalanceResponse
	(*RpcGetBalanceRequests)(nil),  // 6: sf.ethereum.substreams.v1.RpcGetBalanceRequests
	(*RpcGetBalanceResponses)(nil), // 7: sf.ethereum.substreams.v1.RpcGetBalanceResponses
}
var file_sf_ethereum_substreams_v1_rpc_proto_depIdxs = []int32{
	1, // 0: sf.ethereum.substreams.v1.RpcCalls.calls:type_name -> sf.ethereum.substreams.v1.RpcCall
	3, // 1: sf.ethereum.substreams.v1.RpcResponses.responses:type_name -> sf.ethereum.substreams.v1.RpcResponse
	4, // 2: sf.ethereum.substreams.v1.RpcGetBalanceRequests.requests:type_name -> sf.ethereum.substreams.v1.RpcGetBalanceRequest
	5, // 3: sf.ethereum.substreams.v1.RpcGetBalanceResponses.responses:type_name -> sf.ethereum.substreams.v1.RpcGetBalanceResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sf_ethereum_substreams_v1_rpc_proto_init() }
func file_sf_ethereum_substreams_v1_rpc_proto_init() {
	if File_sf_ethereum_substreams_v1_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sf_ethereum_substreams_v1_rpc_proto_rawDesc), len(file_sf_ethereum_substreams_v1_rpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sf_ethereum_substreams_v1_rpc_proto_goTypes,
		DependencyIndexes: file_sf_ethereum_substreams_v1_rpc_proto_depIdxs,
		MessageInfos:      file_sf_ethereum_substreams_v1_rpc_proto_msgTypes,
	}.Build()
	File_sf_ethereum_substreams_v1_rpc_proto = out.File
	file_sf_ethereum_substreams_v1_rpc_proto_goTypes = nil
	file_sf_ethereum_substreams_v1_rpc_proto_depIdxs = nil
}
