// @generated
// This file is @generated by prost-build.
/// Transfers holds the ERC-20 and ERC-721 `Transfer` events decoded out of a block. It carries
/// no RPC result at all, so it streams successfully even when no RPC endpoint is configured on
/// the Firehose instance. Use it to tell "decoding is broken" apart from "the RPC extension is
/// not wired up".
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Transfers {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(message, repeated, tag="2")]
    pub erc20_transfers: ::prost::alloc::vec::Vec<Erc20Transfer>,
    #[prost(message, repeated, tag="3")]
    pub erc721_transfers: ::prost::alloc::vec::Vec<Erc721Transfer>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Erc20Transfer {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub log_index: u32,
    #[prost(string, tag="4")]
    pub contract: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub to: ::prost::alloc::string::String,
    /// Decimal representation of the uint256 amount, a uint64 would silently truncate it.
    #[prost(string, tag="7")]
    pub value: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Erc721Transfer {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub tx_hash: ::prost::alloc::string::String,
    #[prost(uint32, tag="3")]
    pub log_index: u32,
    #[prost(string, tag="4")]
    pub contract: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub to: ::prost::alloc::string::String,
    /// Decimal representation of the uint256 token id, a uint64 would silently truncate it.
    #[prost(string, tag="7")]
    pub token_id: ::prost::alloc::string::String,
}
/// EthCallReport is the outcome of the `rpc::eth_call` invocations performed for one block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EthCallReport {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(enumeration="ReportStatus", tag="2")]
    pub status: i32,
    /// Plain sentences describing anything worth knowing to read the rest, in particular why a
    /// block performed no request and what would make it perform one. Empty on a run where
    /// everything went as expected.
    #[prost(string, repeated, tag="3")]
    pub hints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Contract `balanceOf(address)` was called on.
    #[prost(string, tag="4")]
    pub target_contract: ::prost::alloc::string::String,
    #[prost(enumeration="CallTargetSource", tag="5")]
    pub target_source: i32,
    #[prost(message, repeated, tag="6")]
    pub invocations: ::prost::alloc::vec::Vec<RpcInvocation>,
    #[prost(message, optional, tag="7")]
    pub stats: ::core::option::Option<RpcStats>,
}
/// EthGetBalanceReport is the outcome of the `rpc::eth_get_balance` invocations performed for
/// one block.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EthGetBalanceReport {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(enumeration="ReportStatus", tag="2")]
    pub status: i32,
    /// Plain sentences describing anything worth knowing to read the rest, in particular why a
    /// block performed no request and what would make it perform one. Empty on a run where
    /// everything went as expected.
    #[prost(string, repeated, tag="3")]
    pub hints: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Block parameter sent along each request, either the block's own number as hexadecimal or
    /// the `latest` tag.
    #[prost(string, tag="4")]
    pub block_param: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="5")]
    pub invocations: ::prost::alloc::vec::Vec<RpcInvocation>,
    #[prost(message, optional, tag="6")]
    pub stats: ::core::option::Option<RpcStats>,
}
/// EthMethodsReport bundles both reports so a single module run exercises everything.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EthMethodsReport {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(message, optional, tag="2")]
    pub eth_call: ::core::option::Option<EthCallReport>,
    #[prost(message, optional, tag="3")]
    pub eth_get_balance: ::core::option::Option<EthGetBalanceReport>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcInvocation {
    #[prost(enumeration="InvocationKind", tag="1")]
    pub kind: i32,
    /// Zero-based round this invocation belongs to, a ratio above 1 produces several rounds.
    #[prost(uint32, tag="2")]
    pub round: u32,
    #[prost(uint32, tag="3")]
    pub request_count: u32,
    #[prost(uint32, tag="4")]
    pub success_count: u32,
    #[prost(uint32, tag="5")]
    pub failure_count: u32,
    #[prost(message, repeated, tag="6")]
    pub results: ::prost::alloc::vec::Vec<RpcResult>,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RpcResult {
    /// Address the request was made for, the `balanceOf` argument for eth_call and the queried
    /// account for eth_getBalance.
    #[prost(string, tag="1")]
    pub address: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub failed: bool,
    /// Decimal representation of the returned uint256, empty when the request failed or when the
    /// payload could not be decoded.
    #[prost(string, tag="3")]
    pub value: ::prost::alloc::string::String,
    /// Raw response as returned by the endpoint, hexadecimal with a `0x` prefix.
    #[prost(string, tag="4")]
    pub raw: ::prost::alloc::string::String,
}
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RpcStats {
    #[prost(uint32, tag="1")]
    pub invocation_count: u32,
    #[prost(uint32, tag="2")]
    pub request_count: u32,
    #[prost(uint32, tag="3")]
    pub success_count: u32,
    #[prost(uint32, tag="4")]
    pub failure_count: u32,
}
/// ReportStatus tells a block that performed requests apart from one that performed none, and in
/// the latter case why. A quiet chain, which a testnet usually is, legitimately produces blocks
/// holding nothing to build a request from: that is a property of the chain rather than a problem
/// with the RPC setup under test, and the two must not be confused.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ReportStatus {
    Unspecified = 0,
    /// Requests were performed, `invocations` and `stats` describe them.
    Performed = 1,
    /// The `call_ratio` or `balance_ratio` parameter excluded this block.
    SkippedByRatio = 2,
    /// The block did not carry enough to build a single request. `hints` says what was missing and
    /// what to do about it.
    InsufficientBlockData = 3,
}
impl ReportStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            ReportStatus::Unspecified => "REPORT_STATUS_UNSPECIFIED",
            ReportStatus::Performed => "REPORT_STATUS_PERFORMED",
            ReportStatus::SkippedByRatio => "REPORT_STATUS_SKIPPED_BY_RATIO",
            ReportStatus::InsufficientBlockData => "REPORT_STATUS_INSUFFICIENT_BLOCK_DATA",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REPORT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "REPORT_STATUS_PERFORMED" => Some(Self::Performed),
            "REPORT_STATUS_SKIPPED_BY_RATIO" => Some(Self::SkippedByRatio),
            "REPORT_STATUS_INSUFFICIENT_BLOCK_DATA" => Some(Self::InsufficientBlockData),
            _ => None,
        }
    }
}
/// CallTargetSource says where the contract `balanceOf(address)` was called on came from, the
/// resolution degrading as a block carries less. Anything below BUSIEST_ERC20 means the call was
/// made against a contract that is quite possibly not a token, so an empty response is expected
/// and is not by itself the sign of a broken endpoint.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CallTargetSource {
    Unspecified = 0,
    /// The `call_to` parameter, set directly or through the manifest `networks` section.
    Parameter = 1,
    /// The ERC-20 contract that emitted the most `Transfer` events in the block.
    BusiestErc20 = 2,
    /// An address the block sent a transaction to with a non empty payload, hence one holding code.
    /// Reached when the block carries no ERC-20 transfer at all.
    CalledContract = 3,
}
impl CallTargetSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            CallTargetSource::Unspecified => "CALL_TARGET_SOURCE_UNSPECIFIED",
            CallTargetSource::Parameter => "CALL_TARGET_SOURCE_PARAMETER",
            CallTargetSource::BusiestErc20 => "CALL_TARGET_SOURCE_BUSIEST_ERC20",
            CallTargetSource::CalledContract => "CALL_TARGET_SOURCE_CALLED_CONTRACT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CALL_TARGET_SOURCE_UNSPECIFIED" => Some(Self::Unspecified),
            "CALL_TARGET_SOURCE_PARAMETER" => Some(Self::Parameter),
            "CALL_TARGET_SOURCE_BUSIEST_ERC20" => Some(Self::BusiestErc20),
            "CALL_TARGET_SOURCE_CALLED_CONTRACT" => Some(Self::CalledContract),
            _ => None,
        }
    }
}
/// InvocationKind tells a one-request invocation apart from a batched one. Both go through the
/// same host function, the batched one is what stresses the RPC batching path.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InvocationKind {
    Unspecified = 0,
    Single = 1,
    Batch = 2,
}
impl InvocationKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            InvocationKind::Unspecified => "INVOCATION_KIND_UNSPECIFIED",
            InvocationKind::Single => "INVOCATION_KIND_SINGLE",
            InvocationKind::Batch => "INVOCATION_KIND_BATCH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INVOCATION_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "INVOCATION_KIND_SINGLE" => Some(Self::Single),
            "INVOCATION_KIND_BATCH" => Some(Self::Batch),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
