//! Code shared by the binaries under `src/bin`, which is where the handlers live.
//!
//! This package exercises the two RPC WASM extensions a `fireeth` instance registers,
//! `rpc::eth_call` and `rpc::eth_get_balance`. Each is enabled by its own flag,
//! `--substreams-rpc-endpoints` and `--substreams-rpc-get-balance-endpoints`, and an operator may
//! well have configured only one of them, or neither.
//!
//! A WASM module resolves its imports when it is instantiated rather than when it calls them, so a
//! single binary referencing both extensions fails to instantiate whenever one of the two is
//! unregistered, and it fails for every module of the package, including the ones performing no
//! RPC at all. Splitting the handlers over one binary per extension is what keeps a missing
//! endpoint failing the modules that need it instead of all of them.
//!
//! Nothing here may reference either extension, directly or transitively: this library is linked
//! into all three binaries, and a reference would put the import back into every one of them.

pub mod abi;
pub mod accounts;
pub mod params;
pub mod report;

// Generated by `substreams protogen` out of `proto/`, and committed: regenerating them reaches
// out to the buf remote plugins, which a plain `cargo build` has no business needing.
#[rustfmt::skip]
#[allow(clippy::all)]
pub mod pb;

use substreams::Hex;

/// `Hex::encode` emits lowercase hexadecimal without a prefix, every address and hash we emit
/// goes through here so the output is consistently `0x` prefixed.
pub fn hex0x(bytes: &[u8]) -> String {
    format!("0x{}", Hex::encode(bytes))
}

pub fn decode_hex_address(address: &str) -> Option<Vec<u8>> {
    hex::decode(address.strip_prefix("0x").unwrap_or(address))
        .ok()
        .filter(|bytes| bytes.len() == 20)
}
