#!/bin/bash
# description: prints either 'syncing' if this node is catching up with the network

if command -v geth &> /dev/null; then
	ipc_path="`printf /sf-data/*/ipc`"
	result=`/app/geth attach --exec 'eth.syncing' "$ipc_path" 2> /tmp/geth_error`
	if [[ $? != 0 ]]; then
		echo "Unable to get syncing state correctly"
		cat /tmp/geth_error
		exit 1
	fi

	if printf $result | grep -q ^true$; then
		echo Syncing
	else
		echo "Not syncing (probably live)"
	fi
elif command -v openethereum &> /dev/null; then
    echo "The command '`basename $0`' for OpenEthereum is not supported, please add support for it in firehose-ethereum repository"
    exit 1
else
    echo "This was run on a node where neither Geth nor OpenEthereum could be found, cannot proceed further"
    exit 1
fi
