// Both modules below are generated by `build.rs` from the ABI files under `abi/`, they are not
// meant to be edited by hand and are kept out of Git. Linting them is pointless, the lints would
// have to be fixed in the generator.
#[rustfmt::skip]
#[allow(clippy::all)]
pub mod erc20;
#[rustfmt::skip]
#[allow(clippy::all)]
pub mod erc721;
