name: Buf

on:
  push:
    tags:
      - v*
    branches:
      - develop
      - release/v*
      - feature/*

permissions:
  contents: read
  pull-requests: read

jobs:
  buf:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Buf CI
        uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          lint: false  # Disable lint since it was previously disabled
