name: Build docker image

on:
  push:
    tags:
      - "v*"
    branches:
      - "develop"
      - "release/v*"
      - "feature/*"
      - "fix/*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  setup:
    runs-on: ubuntu-24.04

    env:
      SLACK_IDS: ${{ vars.SLACK_IDS }}

    outputs:
      slack_id: ${{ steps.get-slack-id.outputs.SLACK_ID }}

    steps:
      - name: Check SLACK_IDS env variable
        run: |
          if [ -z "${SLACK_IDS}" ]; then
            echo "The secret 'vars.SLACK_IDS' is empty"
            exit 1
          fi

      - name: Get Slack ID
        id: get-slack-id
        run: |
          SLACK_IDS=$(echo "$SLACK_IDS" | sed 's/\\//g')
          SLACK_ID=$(echo "$SLACK_IDS" | jq -r '.["${{ github.actor }}"]')
          echo "SLACK_ID=$SLACK_ID" >> $GITHUB_OUTPUT

  docker_build:
    needs: [setup]
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            platform_suffix: amd64
            runner: ubuntu-24.04

          - platform: linux/arm64
            platform_suffix: arm64
            runner: ubuntu-24.04-arm

    runs-on: ["${{ matrix.runner }}"]

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract-version
        run: |
          version="edge-${GITHUB_SHA::7}"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            version=${GITHUB_REF#refs/tags/}
          fi

          echo "VERSION=${version}" >> "$GITHUB_OUTPUT"

      - name: Generate docker tags/labels from github build context
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=ref,event=tag,suffix=-${{ matrix.platform_suffix }}
            type=sha,prefix=,priority=300
            type=sha,prefix=,suffix=-${{ matrix.platform_suffix }},priority=300
            type=raw,enable=${{ github.ref == 'refs/heads/develop' }},value=develop
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
          build-args: |
            VERSION=${{ steps.extract-version.outputs.VERSION }}

      - name: Get Job ID from GH API
        id: get_job_id
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs=$(gh api "repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs")
          job_id=$(echo "$jobs" | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
          echo "job_id=$job_id" >> $GITHUB_OUTPUT

      - name: Notify build failure on Slack
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@2.1.0
        with:
          args: |
            :x: <@${{ needs.setup.outputs.slack_id }}> *${{ github.repository }}* Failed building docker image (${{ matrix.platform_suffix }}) from ${{ github.ref_type }} _${{ github.ref_name }}_ (${{ github.actor }}, <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/job/${{ steps.get_job_id.outputs.job_id }}|See Actions Logs>) :broken_heart:

  docker-scout:
    needs: [build]
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: read
      pull-requests: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute short SHA
        id: sha
        run: echo "short=${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Docker Scout AMD64
        uses: docker/scout-action@v1
        with:
          dockerhub-user: ${{ secrets.DOCKER_SCOUT_USER }}
          dockerhub-password: ${{ secrets.DOCKER_SCOUT_PASSWORD }}
          command: cves
          only-severities: critical,high
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.short }}-amd64
          github-token: ${{ secrets.PR_COMMENTER }}
          exit-code: true
          write-comment: true

      - name: Docker Scout ARM64
        uses: docker/scout-action@v1
        with:
          dockerhub-user: ${{ secrets.DOCKER_SCOUT_USER }}
          dockerhub-password: ${{ secrets.DOCKER_SCOUT_PASSWORD }}
          command: cves
          only-severities: critical,high
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.sha.outputs.short }}-arm64
          github-token: ${{ secrets.PR_COMMENTER }}
          exit-code: true
          write-comment: true

  push:
    needs: [setup, build]
    runs-on: ubuntu-24.04

    outputs:
      tags: ${{ steps.meta.outputs.tags }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate docker tags/labels from github build context
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=sha,prefix=,priority=300
            type=raw,enable=${{ github.ref == 'refs/heads/develop' }},value=develop
          flavor: |
            latest=${{ startsWith(github.ref, 'refs/tags/') }}
          sep-tags: ","

      - name: Extract image
        id: image
        run: |
          echo "ID=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Create and push manifest images
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: "${{ steps.meta.outputs.tags }}"
          images: "${{ steps.image.outputs.ID }}-amd64, ${{ steps.image.outputs.ID }}-arm64"
          push: true

      - name: Get Job ID from GH API
        id: get_job_id
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          jobs=$(gh api "repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/attempts/${{ github.run_attempt }}/jobs")
          job_id=$(echo "$jobs" | jq -r '.jobs[] | select(.runner_name=="${{ runner.name }}") | .id')
          echo "job_id=$job_id" >> $GITHUB_OUTPUT

      - name: Notify manifest push failure on Slack
        if: ${{ failure() }}
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@2.1.0
        with:
          args: |
            :x: <@${{ needs.setup.outputs.slack_id }}> *${{ github.repository }}* Failed pushing docker manifest from ${{ github.ref_type }} _${{ github.ref_name }}_ (${{ github.actor }}, <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}/job/${{ steps.get_job_id.outputs.job_id }}|See Actions Logs>) :broken_heart:

  slack-notifications:
    needs: [setup, push]
    runs-on: ubuntu-24.04
    steps:
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: Ilshidur/action-slack@2.1.0
        with:
          args: |
            :done: <@${{ needs.setup.outputs.slack_id }}> *${{ github.repository }}* Success building docker image from ${{ github.ref_type }} _${{ github.ref_name }}_ (${{ github.actor }}) :sparkling_heart: ```${{ needs.push.outputs.tags }}```
